#此文件参考：https://github.com/Mattraks/PULL/blob/main/.github/workflows/Pull.yml
name: Pull-upstream
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1/3 * *
jobs:
  autosync:
    runs-on: ubuntu-latest
    steps:
    - name: AutoBuild-Actions-sync  #openwrt-路由器固件自动编译
      uses: wei/git-sync@v3
      with:
        source_repo: "Hyy2001X/AutoBuild-Actions"
        source_branch: "master"
        destination_repo: "https://Ilris:${{secrets.PAT}}@github.com/Ilris/Openwrt-AutoBuild-Actions.git"
        destination_branch: "main"
        
  delete_workflow_runs: #自动删除Action工作流记录
    runs-on: ubuntu-latest
    needs: autosync
    steps:
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v1.2.2
      with:
        retain_days: 0.02
        keep_minimum_runs: 3
